//论文1: 故障已知Known
PARAM_DEFINE_FLOAT(MY_ATT_P, 3);//8//2
PARAM_DEFINE_FLOAT(MY_ATT_P_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_F_P_P, 1.0);

//PARAM_DEFINE_FLOAT(MY_K_W, 0);
PARAM_DEFINE_FLOAT(MY_K_CP, 1.1);//1500度的时候1适用, 1900度的时候1会炸鸡, 故而设置为0, 尽管1可以提高响应速度 0.8, 0.6呢?
PARAM_DEFINE_FLOAT(MY_K_DVZ, 0.3);

PARAM_DEFINE_FLOAT(MY_POS_P, 0.5);

PARAM_DEFINE_FLOAT(MY_RATE_P, 11);
PARAM_DEFINE_FLOAT(MY_RATE_P_YAW, 0.3);

PARAM_DEFINE_FLOAT(MY_SAT_AD, 0.13);

PARAM_DEFINE_FLOAT(MY_TAU_P_A, 0.0);
PARAM_DEFINE_FLOAT(MY_TAU_P_A_YAW, 0.0);
PARAM_DEFINE_FLOAT(MY_TAU_P_P, 1.2); //1500度左右时1.5可以, 但是1900度转速的时候调至1.3可以减小欧拉角抖动1.2也可
PARAM_DEFINE_FLOAT(MY_TAU_P_P_YAW, 0.1);                                          

PARAM_DEFINE_FLOAT(MY_VEL_P, 0.8);
PARAM_DEFINE_FLOAT(MY_VEL3_I, 0);

//PARAM_DEFINE_FLOAT(MY_UL, 1000);
//PARAM_DEFINE_FLOAT(MY_W_T, 0);
//PARAM_DEFINE_FLOAT(MY_W_S, 0);
