//Unknown ub = 5.5
PARAM_DEFINE_FLOAT(MY_ATT_P, 3);  //减小空气阻尼力矩系数后 改为3, 之前是5
PARAM_DEFINE_FLOAT(MY_ATT_P_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_K_CP, 0.7);//0.7效果最合适此时2 3(顺时针数)两个旋翼转速最为接近, 0.6太小, 1太大会剧烈抖动

PARAM_DEFINE_FLOAT(MY_POS_P, 0.5);

PARAM_DEFINE_FLOAT(MY_RATE_P, 14);
PARAM_DEFINE_FLOAT(MY_RATE_P_YAW, 0.3);

PARAM_DEFINE_FLOAT(MY_SAT_AD, 0.13);

PARAM_DEFINE_FLOAT(MY_TAU_P_A, 0.0);
PARAM_DEFINE_FLOAT(MY_TAU_P_A_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_TAU_P_P, 1.3); //减小空气阻尼力矩系数后 改为1.2
PARAM_DEFINE_FLOAT(MY_TAU_P_P_YAW, 0.1);   

PARAM_DEFINE_FLOAT(MY_VEL_P, 0.8);
