PARAM_DEFINE_FLOAT(MY_ATT_P, 5); //5
PARAM_DEFINE_FLOAT(MY_ATT_P_YAW, 0.0);


PARAM_DEFINE_FLOAT(MY_POS_P, 0.5);

PARAM_DEFINE_FLOAT(MY_RATE_P, 12);
PARAM_DEFINE_FLOAT(MY_RATE_P_YAW, 0.3);

PARAM_DEFINE_FLOAT(MY_SAT_AD, 0.13);

PARAM_DEFINE_FLOAT(MY_TAU_P_A, 0.0);
PARAM_DEFINE_FLOAT(MY_TAU_P_A_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_TAU_P_P, 1.5); 
PARAM_DEFINE_FLOAT(MY_TAU_P_P_YAW, 0.1);   

PARAM_DEFINE_FLOAT(MY_VEL_P, 0.8);
