//论文2: 故障未知 参数更新时间20221007 IMU_INTEG_RATE = 400Hz
PARAM_DEFINE_FLOAT(MY_ATT_P, 3);  //减小空气阻尼力矩系数后 改为3, 之前是5
PARAM_DEFINE_FLOAT(MY_ATT_P_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_K_CP, 0.6);//0.6效果最合适此时2 3(顺时针数)两个旋翼转速最为接近, 更小甚至为0的情况下会不会更好? 之前问题的关键很有可能是IMU_INTEG_RATE参数默认为200Hz的缘故

PARAM_DEFINE_FLOAT(MY_POS_P, 0.3);
PARAM_DEFINE_FLOAT(MY_POS_ALT, 0.6);

PARAM_DEFINE_FLOAT(MY_RATE_P, 14);
PARAM_DEFINE_FLOAT(MY_RATE_P_YAW, 0.3);

PARAM_DEFINE_FLOAT(MY_SAT_AD, 0.15);

PARAM_DEFINE_FLOAT(MY_TAU_P_A, 0.0);
PARAM_DEFINE_FLOAT(MY_TAU_P_A_YAW, 0.0);

PARAM_DEFINE_FLOAT(MY_TAU_P_P, 1.3); 
PARAM_DEFINE_FLOAT(MY_TAU_P_P_YAW, 0.1); 

PARAM_DEFINE_FLOAT(MY_VEL_P, 0.1);
PARAM_DEFINE_FLOAT(MY_VEL_ALT, 1);
